spring:
  groovy:
    template:
      check-template-location: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.20.63:3306/jlxf_0309?useUnicode=true&characterEncoding=UTF8
    username: root
    password: sxkj0818web
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  config: classpath:logback.groovy
sync:
  query:
    sql:
      - index-name: pt_petition_case
        type-name: pt_petition_case
        query-sql: SELECT * FROM pt_petition_case
        count-sql: SELECT count(1) total FROM pt_petition_case
      - index-name: pt_petition_status
        type-name: pt_petition_status
        query-sql: SELECT * FROM pt_petition_status
        count-sql: SELECT count(1) total FROM pt_petition_status
      - index-name: pt_petition_content
        type-name: pt_petition_content
        query-sql: SELECT * FROM pt_petition_content
        count-sql: SELECT count(1) total FROM pt_petition_content
      - index-name: pt_petition_person
        type-name: pt_petition_person
        query-sql: SELECT * FROM pt_petition_person
        count-sql: SELECT count(1) total FROM pt_petition_person
  elasticsearch:
    host: 127.0.0.1
    port: 9200